#!/usr/bin/env php
<?php

use InfoUpdater\InfoUpdater;
use InfoUpdater\UpdateStatusXmlChecker;

require_once __DIR__ . '/vendor/autoload.php';
if (!isset($argv[1])) {
  throw new Exception("Provide file");
}
InfoUpdater::updateInfo($argv[1]) ? exit(0) : exit(1);
