from whitelists.base import whitelist

whitelist.update(
    table="field_data_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "body_value",
        "body_summary",
        "body_format",
    ])

whitelist.update(
    table="field_revision_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "body_value",
        "body_summary",
        "body_format",
    ])

whitelist.add(
    table="content_access",
    columns=[
        "nid",
        "settings",
    ])

whitelist.add(
    table="drupalorg_crosssite_ind_civimembership",
    columns=[
        "user_name",
        "membership_status",
        "expiration_date",
        "updated",
    ])

whitelist.add(
    table="drupalorg_crosssite_org_civimembership",
    columns=[
        "org_name",
        "membership_type",
        "membership_status",
        "expiration_date",
        "updated",
    ])

whitelist.add(
    table="field_data_field_attachments",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_attachments_fid",
        "field_attachments_display",
        "field_attachments_description",
    ])

whitelist.add(
    table="field_data_field_backout_plan",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_backout_plan_value",
        "field_backout_plan_format",
    ])

whitelist.add(
    table="field_data_field_contact",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_contact_target_id",
    ])

whitelist.add(
    table="field_data_field_date",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_value",
        "field_date_format",
    ])

whitelist.add(
    table="field_data_field_description",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_description_value",
        "field_description_format",
    ])

whitelist.add(
    table="field_data_field_impact",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_impact_value",
    ])

whitelist.add(
    table="field_data_field_outage",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_outage_value",
    ])

whitelist.add(
    table="field_data_field_properties",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_properties_tid",
    ])

whitelist.add(
    table="field_data_field_related_issues",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_related_issues_url",
        "field_related_issues_title",
        "field_related_issues_attributes",
    ])

whitelist.add(
    table="field_data_field_status",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_status_value",
    ])

whitelist.add(
    table="field_data_field_summary",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_summary_value",
        "field_summary_format",
    ])

whitelist.add(
    table="field_data_field_time",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_time_value",
        "field_time_format",
    ])

whitelist.add(
    table="field_data_field_ux_review",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_ux_review_value",
    ])

whitelist.add(
    table="field_revision_comment_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "comment_body_value",
        "comment_body_format",
    ])

whitelist.add(
    table="field_revision_field_attachments",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_attachments_fid",
        "field_attachments_display",
        "field_attachments_description",
    ])

whitelist.add(
    table="field_revision_field_backout_plan",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_backout_plan_value",
        "field_backout_plan_format",
    ])

whitelist.add(
    table="field_revision_field_contact",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_contact_target_id",
    ])

whitelist.add(
    table="field_revision_field_date",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_value",
        "field_date_format",
    ])

whitelist.add(
    table="field_revision_field_description",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_description_value",
        "field_description_format",
    ])

whitelist.add(
    table="field_revision_field_outage",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_outage_value",
    ])

whitelist.add(
    table="field_revision_field_properties",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_properties_tid",
    ])

whitelist.add(
    table="field_revision_field_related_issues",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_related_issues_url",
        "field_related_issues_title",
        "field_related_issues_attributes",
    ])

whitelist.add(
    table="field_revision_field_status",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_status_value",
    ])

whitelist.add(
    table="field_revision_field_time",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_time_value",
        "field_time_format",
    ])

whitelist.add(
    table="security_review",
    columns=[
        "namespace",
        "reviewcheck",
        "result",
        "lastrun",
        "skip",
        "skiptime",
        "skipuid",
    ])
