from whitelists.base import whitelist

whitelist.update(
    table="field_data_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "body_value",
        "body_summary",
        "body_format",
    ])

whitelist.update(
    table="field_revision_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "body_value",
        "body_summary",
        "body_format",
    ])

whitelist.add(
    table="content_access",
    columns=[
        "nid",
        "settings",
    ])

whitelist.add(
    table="drupalorg_crosssite_ind_civimembership",
    columns=[
        "user_name",
        "membership_status",
        "expiration_date",
        "updated",
    ])

whitelist.add(
    table="drupalorg_crosssite_org_civimembership",
    columns=[
        "org_name",
        "membership_type",
        "membership_status",
        "expiration_date",
        "updated",
    ])

whitelist.add(
    table="field_data_field_attachments",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_attachments_fid",
        "field_attachments_display",
        "field_attachments_description",
    ])

whitelist.add(
    table="field_data_field_backout_plan",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_backout_plan_value",
        "field_backout_plan_format",
    ])

whitelist.add(
    table="field_data_field_contact",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_contact_target_id",
    ])

whitelist.add(
    table="field_data_field_description",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_description_value",
        "field_description_format",
    ])

whitelist.add(
    table="field_data_field_outage",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_outage_value",
    ])

whitelist.add(
    table="field_data_field_related_issues",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_related_issues_url",
        "field_related_issues_title",
        "field_related_issues_attributes",
    ])

whitelist.add(
    table="field_data_field_status",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_status_value",
    ])

whitelist.add(
    table="field_revision_comment_body",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "comment_body_value",
        "comment_body_format",
    ])

whitelist.add(
    table="field_revision_field_attachments",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_attachments_fid",
        "field_attachments_display",
        "field_attachments_description",
    ])

whitelist.add(
    table="field_revision_field_backout_plan",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_backout_plan_value",
        "field_backout_plan_format",
    ])

whitelist.add(
    table="field_revision_field_contact",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_contact_target_id",
    ])

whitelist.add(
    table="field_revision_field_description",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_description_value",
        "field_description_format",
    ])

whitelist.add(
    table="field_revision_field_outage",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_outage_value",
    ])

whitelist.add(
    table="field_revision_field_related_issues",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_related_issues_url",
        "field_related_issues_title",
        "field_related_issues_attributes",
    ])

whitelist.add(
    table="field_revision_field_status",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_status_value",
    ])

whitelist.add(
    table="security_review",
    columns=[
        "namespace",
        "reviewcheck",
        "result",
        "lastrun",
        "skip",
        "skiptime",
        "skipuid",
    ])

whitelist.add(
    table="field_data_field_change_affects",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_change_affects_target_id",
    ])

whitelist.add(
    table="field_data_field_date_change_completed",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_change_completed_value",
    ])

whitelist.add(
    table="field_data_field_date_scheduled",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_scheduled_value",
        "field_date_scheduled_value2",
    ])

whitelist.add(
    table="field_data_field_depends_on",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_depends_on_target_id",
    ])

whitelist.add(
    table="field_data_field_servers",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_servers_target_id",
    ])

whitelist.add(
    table="field_data_field_shortname",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_shortname_value",
        "field_shortname_format",
    ])

whitelist.add(
    table="field_data_field_url",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_url_url",
        "field_url_title",
        "field_url_attributes",
    ])

whitelist.add(
    table="field_revision_field_change_affects",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_change_affects_target_id",
    ])

whitelist.add(
    table="field_revision_field_date_change_completed",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_change_completed_value",
    ])

whitelist.add(
    table="field_revision_field_date_scheduled",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_date_scheduled_value",
        "field_date_scheduled_value2",
    ])

whitelist.add(
    table="field_revision_field_depends_on",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_depends_on_target_id",
    ])

whitelist.add(
    table="field_revision_field_servers",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_servers_target_id",
    ])

whitelist.add(
    table="field_revision_field_shortname",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_shortname_value",
        "field_shortname_format",
    ])

whitelist.add(
    table="field_revision_field_url",
    columns=[
        "entity_type",
        "bundle",
        "deleted",
        "entity_id",
        "revision_id",
        "language",
        "delta",
        "field_url_url",
        "field_url_title",
        "field_url_attributes",
    ])
